### ISSUE TITLE
Unable to teardown the rook

### ISSUE THREAD

**Issue by khaninejad** [rook/rook.github.io#117]
Hello,

I've followed [this ](https://rook.io/docs/rook/v1.7/ceph-teardown.html)instruction to teardown my rook cluster but it stuck when I try to run the below command:

```
root@tb:/home/xxx/rook/cluster/examples/kubernetes/ceph# kubectl delete -n rook-ceph cephblockpool replicapool
cephblockpool.ceph.rook.io "replicapool" deleted
```

I waited like 24 hours to complete it but, no luck. 
Thank you

**Comment by travisn** [comment]
@khaninejad Was there any data in the cluster remaining? Rook will not delete the CRs if there are rbd images in the pool. The operator log should show errors about why the pool couldn't be deleted. You can also force remove the finalizers as described [here](https://rook.io/docs/rook/v1.7/ceph-teardown.html#removing-the-cluster-crd-finalizer)

**Comment by khaninejad** [comment]
@travisn It was a fresh cluster, 
I followed the link and this is the result:

> The CephBlockPool "replicapool" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}
> The CephCluster "rook-ceph" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}
> The CephFilesystem "myfs" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> The CephObjectStore "my-store" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}
> root@tabm1:/home/shoniz# vi remove.sh
> root@tabm1:/home/shoniz# chmod +x remove.sh
> root@tabm1:/home/shoniz# ./remove.sh
> The CephBlockPool "replicapool" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}
> The CephCluster "rook-ceph" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}
> The CephFilesystem "myfs" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> The CephObjectStore "my-store" is invalid:
> * metadata.finalizers: Invalid value: "": name part must be non-empty
> * metadata.finalizers: Invalid value: "": name part must consist of alphanumeric                                                                 characters, '-', '_' or '.', and must start and end with an alphanumeric charac                                                                ter (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '                                                                ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> * metadata.finalizers: Forbidden: no new finalizers can be added if the object i                                                                s being deleted, found new finalizers []string{""}

**Comment by travisn** [comment]
Where do you see those errors? In the rook operator log?
This sounds similar to #9294. You are using K8s 1.22?

**Comment by travisn** [comment]
Please also open issues on the https://github.com/rook/rook repo, rather than this repo. I'll close this one here.
