### ISSUE TITLE
generate anchor tags for all section headers

### ISSUE THREAD

**Issue by jbw976** [rook/rook.github.io#21]
In the rook.io docs, the experience could be improved if each section header had anchor tags like they do on github.  On github, hovering over a section header provides a little link icon to the left of the header.  When clicking this icon you are given the direct link to this section.

One example is https://github.com/rook/rook/blob/master/Documentation/kubernetes.md#rook-client.  See the attached screenshot.
![screen shot 2017-06-05 at 12 22 19 pm](https://cloud.githubusercontent.com/assets/4313439/26799296/ce9a3a54-49e9-11e7-8282-94cc20e2b718.png)

This makes it much easier to give our users an easy direct link to the relevant documentation section to help with their problem.

Related Jekyll issue: https://github.com/jekyll/jekyll/issues/2690#issuecomment-51159251

**Comment by galexrt** [comment]
@jbw976 Can this issue be closed after #83 has been merged which makes getting a anchored link easier?

**Comment by jbw976** [comment]
yes, this functionality is present and working! 💪
