### ISSUE TITLE
Follow up on moving to new Makefile build method

### ISSUE THREAD

**Issue by thephred** [rook/rook.github.io#50]
As stated in the file, we should get rid of the build directory and move the `preprocess.js` script to root once we know that is is not depended on by old branches of https://github.com/rook/rook

The code that needs to be merged to all active branches of https://github.com/rook/rook is in rook/rook#2497

**Comment by jbw976** [comment]
Both master and the 0.9 branch of `rook/rook` have the necessary changes.  We should be able to follow up on this issue now. 

`master`: https://github.com/rook/rook/pull/2497
`release-0.9`: https://github.com/rook/rook/pull/2658
