### ISSUE TITLE
Broken layout (icon scaling) in "Features of Rook" part

### ISSUE THREAD

**Issue by Dobiasd** [rook/rook.github.io#65]
The "Features of Rook" part of rook.io looks broken on Chrome. Firefox, however, is fine.

Screenshots:
- Chrome 75.0.3770.90 (Official Build) (64-bit): https://i.imgur.com/XBGoz1p.jpg
- Firefox 67.0.2 (64-bit): https://i.imgur.com/S3gkmT5.jpg

@rathpc

**Comment by rathpc** [comment]
Seems like something in the recent updates of Chrome have broken the layout that had been working. Working on a quick fix now.
