### ISSUE TITLE
SEO: Disable indexing of old versions

### ISSUE THREAD

**Issue by onmyflow** [rook/rook.github.io#91]
I've noticed that every time I seach something on google that has to do with rook, I always land on the v0.8 documentation page and not on the latest version.
It would be better if one could give the old versions as well as the master branch a "nodinex" meta tag, so google doesn't index those sites. 
In my opinion the majority of users will always use the latest version of rook thus outweighing the users that still use v0.8.

**Comment by jbw976** [comment]
This is a great idea, thanks for opening this issue @onmyflow.  @galexrt do you know if this is easily supported via config by Gatsby? Hopefully this would be an easy setting to turn on :)

**Comment by galexrt** [comment]
@jbw976 Gatsby? As far as I know Jekyll is used, but yeah that should be possible.

**Comment by jbw976** [comment]
I get Jekyll and Gatsby confused, sorry! 😕 

someone else suggested updating robots.txt to exclude older versions of the docs

**Comment by galexrt** [comment]
@jbw976 We can do it through robots.txt as well though "officially" wildcards [are not supported](https://stackoverflow.com/a/4833663) ;-)

I have created #92 to use the meta noindex tag method.
